version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: 
          pip3 install locust
          /usr/local/bin/locust -f locustfile.py --clients=20 --hatch-rate=1 --num-request=100 --no-web
          name: Locust

workflows:
  main:
    jobs:
      - build-and-test
