version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pip install locust
            locust -f locustfile.py --host https://16wm3zzum0.execute-api.eu-central-1.amazonaws.com/staging-new --headless -u 100 -r 100 --run-time 1m
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
